# Generated by Django 4.2.6 on 2023-10-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0007_remove_dailyjournal_comments_journalcomment_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journals.tag')),
                ('trades', models.ManyToManyField(related_name='trades', to='reports.trade')),
            ],
            bases=('journals.tag',),
        ),
    ]
