export default function MaximizedPlaybookComments(){
    return (
        <div className="overflow-y-auto w-full h-full px-2">
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
        </div>
    )
}