export default function MaximizedPlaybookComments(){
    return (
        <div className="overflow-y-auto bg-green-300 h-[50%]">
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
            <p>Comment</p>
        </div>
    )
}