# Generated by Django 4.2.6 on 2023-11-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0007_remove_dailyjournal_comments_journalcomment_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('market_fundamentals', models.TextField(blank=True, null=True)),
                ('market_technicals', models.TextField(blank=True, null=True)),
                ('ticker_fundamentals', models.TextField(blank=True, null=True)),
                ('ticker_technicals', models.TextField(blank=True, null=True)),
                ('trade_management', models.TextField(blank=True, null=True)),
                ('tape_reading', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='playbook_tags', to='journals.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
