# Generated by Django 4.2.6 on 2023-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
