# Generated by Django 4.2.6 on 2023-11-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0004_playbook_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='comment',
        ),
    ]
