# Generated by Django 4.2.7 on 2023-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0005_remove_playbook_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='play',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='ticker',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
