# Generated by Django 4.2.7 on 2023-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_alter_dailyjournal_tags'),
        ('playbooks', '0006_playbook_play_playbook_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='tags',
            field=models.ManyToManyField(to='journals.tag'),
        ),
    ]
