# Generated by Django 4.2.7 on 2023-11-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_alter_dailyjournal_tags'),
        ('playbooks', '0008_alter_playbook_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='tags',
            field=models.ManyToManyField(blank=True, to='journals.tag'),
        ),
    ]
