# Generated by Django 4.2.6 on 2023-11-01 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor', '0003_traineequestion_answered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineequestion',
            name='answered_by',
            field=models.ManyToManyField(related_name='answered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
