# Generated by Django 4.2.6 on 2023-10-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journalcomment_dailyjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyjournal',
            name='discipline',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyjournal',
            name='patience',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyjournal',
            name='preparation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
