# Generated by Django 4.2.6 on 2023-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_dailyjournal_discipline_dailyjournal_patience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyjournal',
            name='emotional_management',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyjournal',
            name='risk_management',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
