# Generated by Django 4.2.6 on 2023-10-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_dailyjournal_emotional_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjournal',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='journals.journalcomment'),
        ),
        migrations.AlterField(
            model_name='dailyjournal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='journals.tag'),
        ),
    ]
