# Generated by Django 4.2.6 on 2023-10-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_dailyjournal_comments_alter_dailyjournal_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyjournal',
            name='comments',
        ),
        migrations.AddField(
            model_name='journalcomment',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journals.dailyjournal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyjournal',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='journals.tag'),
        ),
    ]
