# Generated by Django 4.2.6 on 2023-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('ticker', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('form_type', models.CharField(max_length=10)),
                ('filed_at', models.CharField()),
            ],
        ),
    ]
