# Generated by Django 4.2.6 on 2023-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_company_filing_companyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
