# Generated by Django 4.2.6 on 2023-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tickers_tickervariables_exdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickervariables',
            name='atr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickervariables',
            name='avg_v',
            field=models.FloatField(null=True),
        ),
    ]
