# Generated by Django 4.2.6 on 2023-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tickervariables_atr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickers',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
